### ISSUE TITLE
ERROR tinycudann_bindings

### ISSUE THREAD

**Issue by OliverV12** [zju3dv/AutoRecon#18]
I was replicating your project and initially installed it with CUDA 12.3. Following your instructions, I set up the environment with Python 3.10 since the 'tiny-cuda' package wasn't available. The environment creation steps are as follows:

conda create --name auto_recon -y python=3.10
conda activate auto_recon
python -m pip install --upgrade pip setuptools

Following your recommendations, I proceeded with the installation of AutoDecomp and I installed PyTorch using the following commands:

conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia

With these commands, I created an environment containing a different version of CUDA (11.7) compared to the system's CUDA (12.3).
The installed version of PyTorch3D obtained from Anaconda Cloud using the command:

conda install pytorch3d -c pytorch3d

is:

pytorch3d                 0.7.5           py310_cu117_pyt1131    pytorch3d

For the 'tiny-cuda' installation, I initially attempted the following command:

pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch

However, the system reported an incompatibility between the CUDA version of 'tiny-cuda' and the system's CUDA version (12.3).

Upon further investigation on this issue at this link:

https://github.com/NVlabs/tiny-cuda-nn/issues/372

I discovered that it's possible to install 'tiny-cuda' with Python 3.10 and CUDA 11.7 (my Anaconda environment). I used the following command for installation:

pip install https://huggingface.co/camenduru/CoDeF/resolve/main/tinycudann-1.7-cp310-cp310-linux_x86_64.whl

This successfully installed 'tiny-cuda', after which I followed all other instructions to complete the project.
However, upon running the command:

bash exps/code-release/run_pipeline_demo_low-res.sh

I encountered an error related to 'tinycuda_bindings':

Error executing job with overrides: ['data_root=data', 'inst_rel_dir=custom_data_example/co3d_chair', 'sparse_recon.n_images=40', 'sparse_recon.force_rerun=True', 'sparse_recon.n_feature_workers=1', 'sparse_recon.n_recon_workers=1', 'triangulation.force_rerun=True', 'triangulation.n_feature_workers=1', 'triangulation.n_recon_workers=1', 'dino_feature.force_extract=True', 'dino_feature.n_workers=1']
Traceback (most recent call last):
  File "/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/cli/inference_transformer.py", line 94, in main
    data: Dict[str, Any] = sfm_preprocess()
  File "/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/decomp/preprocess.py", line 288, in __call__
    return SfMPreprocessWorker(self.cfg, self.cfg.inst_rel_dir, device="cuda")()
  File "/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/decomp/preprocess.py", line 188, in __call__
    self.parse_poses(data)
  File "/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/decomp/preprocess.py", line 206, in parse_poses
    data.update({"poses": colmap_utils.parse_poses(self.rec)})
  File "/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/utils/colmap.py", line 23, in parse_poses
    all_T44_w2c = read_extrinsics(rec)
  File "/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/utils/colmap.py", line 11, in read_extrinsics
    T44_w2c = np.concatenate([np.concatenate([img.rotmat(), img.tvec[:, None]], 1), bottom], 0)
AttributeError: 'pycolmap.Image' object has no attribute 'rotmat'
(pid=3830560) Extracting LoFTR matches: 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 410/410 [06:16<00:00,  1.74it/s]
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/home/shared/anaconda3/envs/auto_recon/bin/ns-train", line 5, in <module>
    from scripts.train import entrypoint
  File "/home/vicari/AutoRecon/scripts/train.py", line 50, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/home/vicari/AutoRecon/nerfstudio/configs/method_configs.py", line 26, in <module>
    from nerfstudio.configs.autorecon import method_configs as autorecon_method_configs
  File "/home/vicari/AutoRecon/nerfstudio/configs/autorecon/__init__.py", line 44, in <module>
    from nerfstudio.fields.sdf_field import SDFFieldConfig
  File "/home/vicari/AutoRecon/nerfstudio/fields/sdf_field.py", line 42, in <module>
    from nerfstudio.field_components.progressive_encoding import ProgressiveEncoding
  File "/home/vicari/AutoRecon/nerfstudio/field_components/progressive_encoding.py", line 5, in <module>
    import tinycudann as tcnn
  File "/home/shared/anaconda3/envs/auto_recon/lib/python3.10/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/shared/anaconda3/envs/auto_recon/lib/python3.10/site-packages/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/home/shared/anaconda3/envs/auto_recon/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/shared/anaconda3/envs/auto_recon/lib/python3.10/site-packages/tinycudann_bindings/_75_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE

Could you provide insights into resolving this error?

**Comment by Zeng-Fan-Yi** [comment]
It seems that the error may appears here in `AttributeError: 'pycolmap. Image' object has no attribute 'rotmat'`，This error is caused by a recent update to pycolmap, and I am also struggling with this error while running this project. If you find a solution, I hope you can communicate with me.

> I was replicating your project and initially installed it with CUDA 12.3. Following your instructions, I set up the environment with Python 3.10 since the 'tiny-cuda' package wasn't available. The environment creation steps are as follows:我复制了你的项目，并最初安装了CUDA 12.3。按照您的指示，我使用Python 3.10设置了环境，因为'tiny-cuda'包不可用。环境创建步骤如下：
> 
> conda create --name auto_recon -y python=3.10 conda activate auto_recon python -m pip install --upgrade pip setuptools
> 
> Following your recommendations, I proceeded with the installation of AutoDecomp and I installed PyTorch using the following commands:根据您的建议，我继续安装AutoDecomp，并使用以下命令安装PyTorch：
> 
> conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia
> 
> With these commands, I created an environment containing a different version of CUDA (11.7) compared to the system's CUDA (12.3). The installed version of PyTorch3D obtained from Anaconda Cloud using the command:使用这些命令，我创建了一个包含不同版本CUDA（11.7）的环境，与系统的CUDA（12.3）相比。 PyTorch3D的安装版本使用以下命令从Anaconda Cloud获得：
> 
> conda install pytorch3d -c pytorch3d
> 
> is:是：
> 
> pytorch3d 0.7.5 py310_cu117_pyt1131 pytorch3d
> 
> For the 'tiny-cuda' installation, I initially attempted the following command:对于'tiny-cuda'安装，我最初尝试了以下命令：
> 
> pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torchpip install git+[https：//github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch](https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch)
> 
> However, the system reported an incompatibility between the CUDA version of 'tiny-cuda' and the system's CUDA version (12.3).但是，系统报告CUDA版本的“tiny-cuda”与系统的CUDA版本（12.3）之间不兼容。
> 
> Upon further investigation on this issue at this link:在此链接上进一步调查此问题：
> 
> [NVlabs/tiny-cuda-nn#372](https://github.com/NVlabs/tiny-cuda-nn/issues/372)
> 
> I discovered that it's possible to install 'tiny-cuda' with Python 3.10 and CUDA 11.7 (my Anaconda environment). I used the following command for installation:我发现可以用Python 3.10和CUDA 11.7（我的Anaconda环境）安装'tiny-cuda'。我使用以下命令进行安装：
> 
> pip install https://huggingface.co/camenduru/CoDeF/resolve/main/tinycudann-1.7-cp310-cp310-linux_x86_64.whlpip install[https：//huggingface.co/camcameru/CoDeF/resolve/main/tinycudann-1.7-cp310-cp310-linux_x86_64.whl](https://huggingface.co/camenduru/CoDeF/resolve/main/tinycudann-1.7-cp310-cp310-linux_x86_64.whl)
> 
> This successfully installed 'tiny-cuda', after which I followed all other instructions to complete the project. However, upon running the command:这成功地安装了'tiny-cuda'，之后我按照所有其他说明完成了项目。 但是，在运行命令时：
> 
> bash exps/code-release/run_pipeline_demo_low-res.sh
> 
> I encountered an error related to 'tinycuda_bindings':我遇到了一个与'tinycuda_bindings'相关的错误：
> 
> Error executing job with overrides: ['data_root=data', 'inst_rel_dir=custom_data_example/co3d_chair', 'sparse_recon.n_images=40', 'sparse_recon.force_rerun=True', 'sparse_recon.n_feature_workers=1', 'sparse_recon.n_recon_workers=1', 'triangulation.force_rerun=True', 'triangulation.n_feature_workers=1', 'triangulation.n_recon_workers=1', 'dino_feature.force_extract=True', 'dino_feature.n_workers=1'] Traceback (most recent call last): File "/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/cli/inference_transformer.py", line 94, in main data: Dict[str, Any] = sfm_preprocess() File "/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/decomp/preprocess.py", line 288, in **call** return SfMPreprocessWorker(self.cfg, self.cfg.inst_rel_dir, device="cuda")() File "/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/decomp/preprocess.py", line 188, in **call** self.parse_poses(data) File "/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/decomp/preprocess.py", line 206, in parse_poses data.update({"poses": colmap_utils.parse_poses(self.rec)}) File "/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/utils/colmap.py", line 23, in parse_poses all_T44_w2c = read_extrinsics(rec) File "/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/utils/colmap.py", line 11, in read_extrinsics T44_w2c = np.concatenate([np.concatenate([img.rotmat(), img.tvec[:, None]], 1), bottom], 0) AttributeError: 'pycolmap.Image' object has no attribute 'rotmat' (pid=3830560) Extracting LoFTR matches: 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 410/410 [06:16<00:00, 1.74it/s] Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace. Traceback (most recent call last): File "/home/shared/anaconda3/envs/auto_recon/bin/ns-train", line 5, in from scripts.train import entrypoint File "/home/vicari/AutoRecon/scripts/train.py", line 50, in from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion File "/home/vicari/AutoRecon/nerfstudio/configs/method_configs.py", line 26, in from nerfstudio.configs.autorecon import method_configs as autorecon_method_configs File "/home/vicari/AutoRecon/nerfstudio/configs/autorecon/**init**.py", line 44, in from nerfstudio.fields.sdf_field import SDFFieldConfig File "/home/vicari/AutoRecon/nerfstudio/fields/sdf_field.py", line 42, in from nerfstudio.field_components.progressive_encoding import ProgressiveEncoding File "/home/vicari/AutoRecon/nerfstudio/field_components/progressive_encoding.py", line 5, in import tinycudann as tcnn File "/home/shared/anaconda3/envs/auto_recon/lib/python3.10/site-packages/tinycudann/**init**.py", line 9, in from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding File "/home/shared/anaconda3/envs/auto_recon/lib/python3.10/site-packages/tinycudann/modules.py", line 51, in _C = importlib.import_module(f"tinycudann_bindings._{cc}_C") File "/home/shared/anaconda3/envs/auto_recon/lib/python3.10/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ImportError: /home/shared/anaconda3/envs/auto_recon/lib/python3.10/site-packages/tinycudann_bindings/_75_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE执行带有覆盖的作业时出错：'data_root= data'，'inst_rel_dir=custom_data_example/co3d_chair'，'sparse_recon.n_images= 40'，'sparse_recon.force_workers = True'，'sparse_recon.n_feature_workers= 1'，'sparse_recon.n_recon_workers= 1'，'triangulation.force_workers = True'，' triangulation.n_feature_workers= 1'，'triangulation.n_recon_workers= 1'，'dino_feature.force_extract= True'，'dino_feature.n_workers=1'] 回溯（最近的呼叫最后一次）： 文件“/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/auto-decomp/inference_Transformer.py”，第94行，在main中 data：Dict[str，Any] = sfm_preprocess（） 文件“/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/decomp/preprocess.py“，第288行，调用中 return SfMPreprocessWorker（self.cfg，self.cfg.inst_rel_dir，device=“cuda”）（） 文件“/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/decomp/preprocess.py“，第188行，调用中 self.parse_poses（data） 文件“/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/decomp/preprocess.py“，第206行，在parse_poses中 data.update（{“poses”：colmap_utils.parse_poses（self.rec）}） 文件“/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/utils/colmap.py“，第23行，parse_poses中 all_T44_w2c = read_extrinsics（rec） 文件“/home/vicari/AutoRecon/third_party/AutoDecomp/auto_decomp/utils/colmap.py“，第11行，read_extrinsics T44_w2c = np.concatenate（[np.concatenate（[img.rotmat（），img.tvec[：，None]]，1），bottom]，0） AttributeError：'pycolmap.Image'对象没有属性'rotmat' (pid=3830560）提取LoFTR匹配：0：100%| ███████████████████████████████████████████████████████████████████████████████████████████████████████████| 410/410 [06：16< 00：00，1.74it/s] 设置环境变量HYPERFULL_ERROR=1以获得完整的堆栈跟踪。 回溯（最近的呼叫最后一次）： 文件“/home/shared/anaconda 3/envs/auto_recon/bin/ns-train”，第5行，在 从脚本.train导入入口点 文件“/home/vicari/AutoRecon/scripts/train.py“，第50行， 从nerfstudio. functions.method_functionsimport AnnotatedBaseConfigUnion 文件“/home/vicari/AutoRecon/nerfstudio/mysql/method_mysql.py”，第26行， 从nerfstudio. autorecon.autorecon导入方法_autorecon_method_autorecon 文件“/home/vicari/AutoRecon/nerfstudio/nums/autorecon/init.py“，第44行， 从nerfstudio.fields.sdf_field导入SDFFieldConfig 文件“/home/vicari/AutoRecon/nerfstudio/fields/sdf_field.py”，第42行， 从nerfstudio.field_components.progressive_encoding导入ProgressiveEncoding 文件“/home/vicari/AutoRecon/nerfstudio/field_components/progressive_encoding.py”，第5行， 将tinycudann导入为tcnn 文件“/home/shared/anaconda 3/envs/auto_recon/lib/python3.10/site-packages/tinycudann/init.py”，第9行， 从tinycudann.modules导入free_temporary_memory，NetworkWithInputEncoding，Network，Encoding 文件“/home/shared/anaconda 3/envs/auto_recon/lib/python3.10/site-packages/tinycudann/modules.py”，第51行， C = importlib.import_module（f“tinycudann_bindings. {cc}_C”） 文件“/home/shared/anaconda 3/envs/auto_recon/lib/python3.10/importlib/init.py”，第126行，在import_module中 return _引导程序._ gcd_import（名称[级别：]，程序包，级别） ImportError：/home/shared/anaconda3/envs/auto_recon/lib/python3.10/site-packages/tinycudann_bindings/_75_C.cpython-310-x86_64-linux-gnu.so：undefined symbol：_ZN3c104cuda20CUDAC achingAllocator9allocatorE
> 
> Could you provide insights into resolving this error?你能提供解决这个错误的见解吗？
