### ISSUE TITLE
pycolmap.TwoViewGeometryOptions  Error，[custom_data_example/co3d_chair] Unknown error: verify_matches():

### ISSUE THREAD

**Issue by adkAurora** [zju3dv/AutoRecon#19]
**Describe the bug**

2024-02-20 14:42:58.044 | WARNING  | auto_decomp.sfm.sfm:main:632 | - [custom_data_example/co3d_chair] Unknown error: verify_matches(): incompatible function arguments. The following argument types are supported:
    1. (database_path: str, pairs_path: str, options: pycolmap.TwoViewGeometryOptions = <pycolmap.TwoViewGeometryOptions object at 0x7fb47206e270>) -> None

Invoked with: PosixPath('assets/custom_data_example/co3d_chair/sfm_spp-spg_sequential_np-10_nimgs-40/sfm/database.db'), PosixPath('assets/custom_data_example/co3d_chair/sfm_spp-spg_sequential_np-10_nimgs-40/pairs-sfm_seq-loop-det_n10.txt'); kwargs: max_num_trials=20000, min_inlier_ratio=0.1
2024-02-20 14:42:59.374 | INFO     | __main__:main:87 | - Triangulating LoFTR matches
2024-02-20 14:43:03,722 INFO worker.py:1724 -- Started a local Ray instance.
2024-02-20 14:43:05.041 | INFO     | auto_decomp.sfm.sfm:reconstruct_instance:449 | - Reconstruction directory: triangulate_loftr-720000_sequential_np-10
2024-02-20 14:43:05.046 | INFO     | auto_decomp.sfm.sfm:read_write_cache:361 | - Using cached sfm_dire as renference: assets/custom_data_example/co3d_chair/sfm_spp-spg_sequential_np-10_nimgs-40/manhattan
2024-02-20 14:43:05.051 | INFO     | auto_decomp.sfm.sfm:read_write_cache:369 | - Cache updated: assets/custom_data_example/co3d_chair/.cache.json
Error executing job with overrides: ['data_root=assets/', 'inst_rel_dir=custom_data_example/co3d_chair', 'sparse_recon.n_images=40', 'sparse_recon.force_rerun=True', 'sparse_recon.n_feature_workers=1', 'sparse_recon.n_recon_workers=1', 'triangulation.force_rerun=True', 'triangulation.n_feature_workers=1', 'triangulation.n_recon_workers=1', 'dino_feature.force_extract=True', 'dino_feature.n_workers=1']
Traceback (most recent call last):
  File "AutoRecon/third_party/AutoDecomp/auto_decomp/cli/inference_transformer.py", line 88, in main
    sfm.main(cfg.triangulation)
  File "AutoRecon/third_party/AutoDecomp/auto_decomp/sfm/sfm.py", line 610, in main
    reconstruct_instance(copy.deepcopy(args), args.inst_rel_dir, *_queue_args, task_id=0)
  File "AutoRecon/third_party/AutoDecomp/auto_decomp/sfm/sfm.py", line 465, in reconstruct_instance
    references = parse_images_from_reference_model(ref_sfm_dir)
  File "AutoRecon/third_party/AutoDecomp/auto_decomp/sfm/sfm.py", line 386, in parse_images_from_reference_model
    rec = pycolmap.Reconstruction(sfm_ref_dir)
ValueError: [reconstruction.h:62] Check Failed: ExistsReconstruction(path) cameras, images, points3D not found at assets/custom_data_example/co3d_chair/sfm_spp-spg_sequential_np-10_nimgs-40/manhattan

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by adkAurora** [comment]
fix
